config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :doctors, except: :show
  resources :patients, except: :show
  resources :appointments, except: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  validates :starts_at, presence: true, uniqueness: { scope: :doctor_id }, appointment_time: { type: 'start_time' }
  validates :ends_at, presence: true, appointment_time: { type: 'end_time' }, appointment_duration: true
  validates :patient, presence: true
  validates :doctor, presence: true

  scope :finished, -> { where('ends_at < ?', Time.now) }

  def starts_at=(start_date)
    return unless start_date.present?

    start_date = DateTime.new(*start_date.sort.to_h.values.map(&:to_i)) if start_date.is_a? Hash
    start_date = start_date.to_time if start_date.is_a? String
    super(start_date) if start_date.present?
    self.ends_at = start_date + 30.minutes
  end
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  validates :name, presence: true
  validates :crm, presence: true, uniqueness: { scope: :crm_uf }, numericality: { only_integer: true }
  validates :crm_uf, presence: true

  has_many :appointments, dependent: :restrict_with_error
  has_many :patients, through: :appointments
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  validates :name, presence: true
  validates :birth_date, presence: true
  validates :cpf, presence: true, cpf: true, uniqueness: { case_sensitive: true }

  has_many :appointments
  has_many :doctors, through: :appointments

  def cpf=(cpfnumber)
    super(cpfnumber.gsub(/[.-]/, '')) if cpfnumber.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[edit update destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit; end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_path, notice: 'Cadastro realizado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointments_path, notice: 'Cadastro atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_path, notice: 'Cadastro excluído com sucesso.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:starts_at, :ends_at, :doctor_id, :patient_id)
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :set_doctor

  def index
    @appointments = @doctor&.appointments&.finished&.count || Appointment.finished.count
    @consulted_patients = @doctor&.appointments&.finished&.pluck(:patient_id)&.uniq&.count || Appointment.pluck(:patient_id)&.uniq&.count
  end

  private

  def set_doctor
    @doctor = Doctor.find(params['doctor']) if params['doctor'].present?
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[edit update destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all.decorate
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit; end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctors_path, notice: 'Cadastro realizado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctors_path, notice: 'Cadastro atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    respond_to do |format|
      if @doctor.destroy
        format.html { redirect_to doctors_path, notice: 'Cadastro excluído com sucesso.' }
      else
        format.html { redirect_to doctors_path, notice: 'O médico possui pacientes vinculados.' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def doctor_params
    params.require(:doctor).permit(:name, :crm, :crm_uf)
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  before_action :set_patient, only: %i[edit update destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all.decorate
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit; end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_path, notice: 'Cadastro realizado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_path, notice: 'Cadastro atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_path, notice: 'Cadastro excluído com sucesso.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id]).decorate
  end

  # Only allow a list of trusted parameters through.
  def patient_params
    params.require(:patient).permit(:name, :birth_date, :cpf)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

module PatientsHelper
end

app/views/appointments/_appointment.html.erb
<tr>
  <td><%= appointment.starts_at.strftime("%d/%m/%Y") %></td>
  <td><%= appointment.starts_at.strftime("%H:%M") %> - <%= appointment.ends_at.strftime("%H:%M") %></td>
  <td><%= appointment.doctor.decorate.title_name %></td>
  <td><%= appointment.patient.name %></td>
  <td>
    <%= link_to edit_appointment_path(appointment), 
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Editar' } do %>
      <i class="material-icons">edit</i>
    <% end %>
    <%= link_to appointment, method: :delete,
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Excluir', confirm: 'Tem certeza?' } do %>
      <i class="material-icons">delete</i>
    <% end %>
  </td>
<tr>

app/views/appointments/_form.html.erb
<div class="row">
  <%= form_with(model: appointment, local: true) do |form| %>
    <% if appointment.errors.any? %>
      <div id="error_explanation">
        <h5><%= pluralize(patient.errors.count, "erro") %> no formulário:</h5>
        <ul>
          <% appointment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="input-field col s6"> 
        <%= form.select :doctor_id, options_from_collection_for_select(Doctor.all.decorate, 'id', 'title_name'), include_blank: "Selecione o médico" %>
      </div>
      <div class="input-field col s6"> 
        <%= form.select :patient_id, options_from_collection_for_select(Patient.all, 'id', 'name'), include_blank: "Selecione o paciente" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 datetime-select"> 
        <%= form.datetime_select :starts_at, default: Date.today %>
        </div>
    </div>
    <div class="actions">
      <%= link_to 'Voltar', appointments_path, class: 'btn-flat' %>
      <%= form.submit 'Cadastrar', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/appointments/edit.html.erb
<h1>Editar Consulta</h1>

<%= render 'form', appointment: @appointment %>

app/views/appointments/index.html.erb
<h1>Consultas</h1>

<%= link_to 'Cadastrar consulta', new_appointment_path, class: 'right waves-effect waves-light btn' %>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Horário</th>
      <th>Médico</th>
      <th>Paciente</th>
      <th>Opções</th>
    </tr>
  </thead>

  <tbody>
    <%= render @appointments %>
  </tbody>
</table>

app/views/appointments/new.html.erb
<h1>Cadastrar consulta</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/dashboard/_search.html.erb
<%= form_with local: true, method: :get do |f| %>
    <div class="row">
        <div class="col s10">
        <%= f.select "doctor",
            options_from_collection_for_select(Doctor.all.decorate, 'id', 'title_name',  @doctor&.id),
            include_blank: "Todos os médicos", class: 's8' %>
        </div>
        <div class="col s2">
            <%= f.submit 'Buscar', class: 'btn' %>
        </div>
    </div>
<% end %>

app/views/dashboard/index.html.erb
<div class="row" id="dashboard">
    <div class="col s12">
        <h1>Dashboard</h1>
            <%= render 'dashboard/search' %>
        <div id="data">
            <div class="row">
                <div class="col s12 m3">
                    <div class="card blue-grey darken-1">
                        <div class="card-content white-text center-align">
                            <span class="card-title">Consultas realizadas</span>
                            <span class="center-align"> <%= @appointments %> Consultas</span>
                        </div>
                    </div>
                </div>
                <div class="col s12 m3">
                    <div class="card blue-grey darken-1">
                        <div class="card-content white-text center-align">
                            <span class="card-title">Pacientes atendidos</span>
                            <span class="center-align"> <%=  @consulted_patients %> Pacientes</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/doctors/_doctor.html.erb
<tr>
  <td colspan="4"><%= doctor.name %></td>
  <td><%= doctor.full_crm %></td>
  <td>
    <%= link_to edit_doctor_path(doctor), 
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Editar' } do %>
      <i class="material-icons">edit</i>
    <% end %>
    <%= link_to doctor, method: :delete,
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Excluir', confirm: 'Tem certeza?' } do %>
      <i class="material-icons">delete</i>
    <% end %>
  </td>
</tr>

app/views/doctors/_form.html.erb
<div class='row'>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
        <h5><%= pluralize(doctor.errors.count, "erro") %> no formulário:</h5>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: doctor, local: true, class: 'col s12') do |form| %>
    <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :name, class: "validate" ,required: true %>
        <label for="doctor_name">Nome completo</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s4">
        <%= form.text_field :crm, class: "validate", required: true %>
        <label for="doctor_crm">CRM</label>
      </div>
      <div class="input-field col s2">
        <%= form.text_field :crm_uf, class: "validate", required: true %>
        <label for="doctor_crm_uf">CRM UF</label>
      </div>
    </div>

    <div class="actions">
      <%= link_to 'Voltar', doctors_path, class: 'btn-flat' %>
      <%= form.submit 'Cadastrar', class: 'btn' %>
    </div>
  <% end %>
</div>
<script>
  M.updateTextFields();
</script>

app/views/doctors/edit.html.erb
<h1>Editar Médico</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<h1>Médicos</h1>


<%= link_to 'Cadastrar médico', new_doctor_path, class: 'right waves-effect waves-light btn' %>

<table class="responsive-table highlight centered">
  <thead>
    <tr>
      <th colspan="4">Nome</th>
      <th>CRM/UF</th>
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    <%= render @doctors %>
  </tbody>
</table>

app/views/doctors/new.html.erb
<h1>Cadastrar médico</h1>

<%= render 'form', doctor: @doctor %>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to 'BuiltClinic', root_path, class: "brand-logo center" %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Médicos', doctors_path %></li>
      <li><%= link_to 'Pacientes', patients_path %></li>
      <li><%= link_to 'Consultas', appointments_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_toast.html.erb
<% if notice %>
  <script type="text/javascript">
    M.toast({ html: '<%= notice %>', displayLength: 4000})
  </script>
<% end %>
<% if alert %>
  <script type="text/javascript">
    M.toast({ html: '<%= notice %>', displayLength: 4000})
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuiltClinic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/toast' %>
    <!-- Initialize Materialize js -->
    <script>
      M.AutoInit()
      M.updateTextFields();
    </script>
  </body>
</html>

app/views/patients/_form.html.erb
<div class="row">
  <%= form_with(model: patient, local: true) do |form| %>
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <h5><%= pluralize(patient.errors.count, "erro") %> no formulário:</h5>

        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :name, class: "validate" ,required: true %>
        <label for="patient_name">Nome completo</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s3 active">
        <%= form.text_field :cpf, class: "validate", required: true %>
        <label for="patient_cpf">CPF</label>
      </div>
      <div class="input-field col s3 active">
        <%= form.date_field :birth_date, class: "validate ", required: true, value: Date.today %>
        <label for="patient_birth_date" class="active">Data de nascimento</label>
      </div>
    </div>

    <div class="actions">
      <%= link_to 'Voltar', patients_path, class: 'btn-flat' %>
      <%= form.submit 'Cadastrar', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/patients/_patient.html.erb
<tr>
  <td colspan="4"><%= patient.name %></td>
  <td><%= patient.birth_date.strftime("%d/%m/%Y") %></td>
  <td><%= patient.cpf_formatted %></td>
  <td>
    <%= link_to edit_patient_path(patient), 
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Editar' } do %>
      <i class="material-icons">edit</i>
    <% end %>
    <%= link_to patient, method: :delete,
        class: 'btn waves-effect waves-light btn-small icon-button tooltipped', 
        data: { position: 'top', tooltip: 'Excluir', confirm: 'Tem certeza?' } do %>
      <i class="material-icons">delete</i>
    <% end %>
  </td>
</tr>

app/views/patients/edit.html.erb
<h1>Editar Paciente</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1>Pacientes</h1>

<%= link_to 'Cadastrar paciente ', new_patient_path, class: 'right waves-effect waves-light btn' %>

<table class="responsive-table highlight centered">
  <thead>
    <tr>
      <th colspan="4">Nome</th>
      <th>Data de Nascimento</th>
      <th>CPF</th>
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    <%= render @patients %>
  </tbody>
</table>

app/views/patients/new.html.erb
<h1 class="header">Cadastrar paciente</h1>

<%= render 'form', patient: @patient %>